name-template: '$RESOLVED_VERSION'
tag-template: '$TAG_NAME'
template: |
  ## 更新内容

  $CHANGES

categories:
  - title: '🚀 新功能'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
      - 'fix'
  - title: '🔧 其他更新'
    labels:
      - 'chore'
      - 'maintenance'

change-template: '- $TITLE (@$AUTHOR)'
change-title-escapes: '\<*_&'
